"use client"
// import Footer from "@/layout/Footer";
// import { getMetadata } from "@/lib/action/PubilcCommon";
// import { CompanyMeta } from "@/lib/type/CommonType";
// import type { Metadata } from "next";
import React, { useEffect, useState } from "react";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

type Particle = {
  id: number;
  size: number;
  left: string;
  top: string;
  duration: number;
};


export default function  AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>
) {


    const [particles, setParticles] = useState<Particle[]>([]);
  
    useEffect(() => {
      const particleCount = 30;
      const generatedParticles: Particle[] = [];
  
      for (let i = 0; i < particleCount; i++) {
        const size = Math.random() * 3 + 2;
        const left = `${Math.random() * 100}vw`;
        const top = `${Math.random() * 100}vh`;
        const duration = Math.random() * 20 + 10;
  
        generatedParticles.push({
          id: i,
          size,
          left,
          top,
          duration,
        });
      }
  
      setParticles(generatedParticles);
    }, []);
  
    return (
      <div className="relative min-h-screen overflow-hidden bg-black ">
        {/* Particles */}
        {particles.map((p) => (
          <div
            key={p.id}
            className="absolute bg-yellow-400 rounded-full z-0"
            style={{
              width: `${p.size}px`,
              height: `${p.size}px`,
              left: p.left,
              top: p.top,
              animation: `float ${p.duration}s linear infinite`,
            }}
          />
        ))}
  
        <div className="relative z-10 max-w-5xl mx-auto px-4 py-8">
          {/* Logo */}
          <div className="flex items-center mb-8">
            <div className="w-12 h-12 bg-gradient-to-br from-yellow-400 to-yellow-200 transform rotate-45 shadow-lg relative mr-4">
              <div className="absolute inset-2 bg-black"></div>
              <div className="absolute inset-[20%] bg-gradient-to-br from-yellow-400 to-yellow-200"></div>
            </div>
            <h1 className="text-2xl font-extrabold bg-gradient-to-r from-yellow-400 to-yellow-200 bg-clip-text text-transparent drop-shadow-md">
              MOREDEALSX
            </h1>
          </div>
  
          {/* Login Box */}
          {children}
        </div>
  
        <style jsx>{`
          @keyframes float {
            0% {
              transform: translateY(0) scale(1);
              opacity: 1;
            }
            50% {
              transform: translateY(-30px) scale(1.2);
              opacity: 0.7;
            }
            100% {
              transform: translateY(0) scale(1);
              opacity: 1;
            }
          }
        `}</style>
      </div>
    );
}
