import Footer from "@/layout/Footer";
import { getMetadata } from "@/lib/action/PubilcCommon";
import { CompanyMeta } from "@/lib/type/CommonType";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function  LandingLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const MetaDatas : CompanyMeta = await getMetadata();

  return (
        <React.Fragment>
        {children}
        <Footer data={MetaDatas}/>
        </React.Fragment>
  );
}
